spring:
  application:
    name: server-api
  mail:
    host: smtp.gmail.com
    port: 587
    username: mapharitezeey004@gmail.com
    password: rrcpyoznjzoodmkr
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  datasource:
    url: jdbc:postgresql://localhost:5432/serveme_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # can be 'validate', 'create', 'create-drop', 'update', or 'none'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 100 # 5 min
    refreshTokenExpiration: 604800 # 7 days