spring:
  application:
    name: server-api

  datasource:
    url: jdbc:postgresql://localhost:5432/serveme_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # can be 'validate', 'create', 'create-drop', 'update', or 'none'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
